#Basic workflow for github action

#Define name of github action
name: Docker Build and Push

#Control when the action will be run. Triger the workflow on push or pull request event on master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Create  a job section with one job build
jobs:
  
  build:

    #specify the os on which the job will run
    runs-on: ubuntu-latest

    #Create a steps sections for the sequence of steps to complete the job
    steps:
      
      - 
      #Cheout existing code and reference it with the latest commits
        name: Checkout
        uses: actions/checkout@v2
      - 
      #set up QEMU which will create excecution environments for our containers
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
      #Set up Docker Buildx which will provide a more extensive interface to build our docker image
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
      #Login to dockerhub
        name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
      #Build and push image
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: githuma/python-helloworld:latest
      
