#Basic workflow for github action

#Define name of github action
name: Docker Build and Push

#Control when the action will be run. Triger the workflow on push or pull request event on master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Create  a job section with one job build
jobs:
  
  build:

    #specify the os on which the job will run
    runs-on: ubuntu-latest

    #Create a steps sections for the sequence of steps to complete the job
    steps:
      #Cheout existing code and reference it with the latest commits
      - 
        name: Checkout
        uses: actions/checkout@v2
      
